/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylwang_ifacerecognition_DetectionBasedTracker */

#ifndef _Included_com_ylwang_ifacerecognition_DetectionBasedTracker
#define _Included_com_ylwang_ifacerecognition_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeSetFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeEqualizeLeftAndRightHalves
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeEqualizeLeftAndRightHalves
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeGetPreprocessingImage
 * Signature: (JJJII)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeGetPreprocessingImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeTestDataTrans
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeTestDataTrans
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeGetSimilarity
 * Signature: (JJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeGetSimilarity
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeCreateModel
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeCreateModel
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativelearnCollectedFaces
 * Signature: (JLjava/lang/String;Ljava/lang/String;JJI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativelearnCollectedFaces
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeUpdate
 * Signature: (JLjava/lang/String;Ljava/lang/String;JJI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeUpdate
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativePredict
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativePredict
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_DetectionBasedTracker
 * Method:    nativeFindIrisCenter
 * Signature: (JJDD)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeFindIrisCenter
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
